# Template PHP Bui

image: samueldebruyn/debian-git
pipelines:
  default:
        - step:
            script:
              - git push https://heroku:92d3b63d-f850-4967-a5cd-867e97c375a6@git.heroku.com/facebook-test.git HEAD