# Template PHP Bui
image: node:6
clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          script:
            - git push -f https://heroku:92d3b63d-f850-4967-a5cd-867e97c375a6@git.heroku.com/facebook-test.git master